trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    terraform init
    terraform plan -out=tfplan -input=false
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply -input=false tfplan
  displayName: 'Terraform Apply'
